version: '3.8'

services:
  # -------------------- Backend --------------------
  backend:
    build:
      context: ./backend
      args:
        REPO_URL: https://github.com/SQLutions-FATEC/API-4-Semestre-Backend.git
        GIT_BRANCH: develop-1
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://custom-postgres:5432/api
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - custom-postgres

  # -------------------- Frontend --------------------
  frontend:
    build:
      context: ./frontend
      args:
        REPO_URL: https://github.com/SQLutions-FATEC/API-4-Semestre-Frontend.git
        GIT_BRANCH: develop-1
    container_name: vue-app
    ports:
      - "80:80"
    depends_on:
      - backend

  # -------------------- Database --------------------
  custom-postgres:
    build: ./postgres
    container_name: psql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
